server:
  port: 8080
spring:
  redis:
    host: 192.168.13.128
    port: 6379
    password: drcom
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 8
        min-idle: 0